version: '3'

services:
  nextjs-app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - IP_API_KEY=${IP_API_KEY}

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs-app
